kind: ConfigMap
apiVersion: v1
metadata:
  name: scrabble-search
  namespace: default
data:
  main.rb: |-
    #! /usr/bin/ruby
    require 'sinatra'
    $stdout.sync = true # for some reason stdout doesn't show up in container without that

    $words_file_location = "/tmp/all_words.txt"
    $all_words = []

    def load_words
      puts "Reading dictionary from #{$words_file_location}..."
      File.foreach($words_file_location) { |line| $all_words << line.strip }
      puts "Loaded #{$all_words.size} words."
    end

    def find_matches(search)
      regex = Regexp.new("^#{search}$").freeze
      return $all_words.select { |candidate| regex.match?(candidate) }
    end

    def create_form
      "<form method='GET' action='/'> <input type='text' name='query' autofocus> </form>"
    end

    def format_response(matches)
      words = "<pre>" + matches.map { |word| "- #{word}" }.join("\n") + "</pre>"
      return create_form + words
    end

    def start_server
      set :bind, '0.0.0.0'

      get '/' do
        query = params['query']
        if (query == nil)
          return create_form
        end

        puts "Searching for '#{query}' ..."
        matches = find_matches(query)
        puts "Found #{matches.size} matching words."

        return format_response(matches)
      end
    end

    load_words
    start_server

  entrypoint.sh: |-
    #! /bin/bash
    set -e

    DICTIONARY_URL="https://sjp.pl/sl/growy/sjp-20221023.zip"
    DICTIONARY_FILE_ORIGINAL_FILENAME="slowa.txt"

    apt-get update
    apt-get -y install unzip curl ruby ruby-sinatra language-pack-pl
    cd /tmp
    curl --output sjp.zip ${DICTIONARY_URL}
    unzip sjp.zip
    mv ${DICTIONARY_FILE_ORIGINAL_FILENAME} all_words.txt

    # Force PL locale - otherwise Ruby errors out on regex matching
    export LANG=pl_PL.UTF-8
    export LANGUAGE=pl_PL.UTF-8
    export LC_ALL=pl_PL.UTF-8
    ruby /scripts/main.rb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrabble-search
  namespace: default
spec:
  selector:
    matchLabels:
      app: scrabble-search
  template:
    metadata:
      labels:
        app: scrabble-search
    spec:
      containers:
      - name: scrabble-search
        image: ubuntu:latest
        args:
        - bash 
        - -c
        - 'bash /scripts/entrypoint.sh'
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: scrabble-search

---
apiVersion: v1
kind: Service
metadata:
  name: scrabble-search
  namespace: default
spec:
  selector:
    app: scrabble-search
  ports:
  - port: 4567
    targetPort: 4567

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scrabble-search
spec:
  rules:
  - host: scrabble-search.kelog.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scrabble-search
            port:
              number: 4567

